#!/usr/bin/env bash
# Blocks Bash-level blind overwrites/deletes of .dev.vars / .env* files.
#
# Incident: a `printf ... > .dev.vars` overwrite destroyed a real
# CLOUDFLARE_D1_TOKEN with no backup, and it had to be regenerated by hand
# from the Cloudflare dashboard. These files can hold credentials that are
# shown only once at creation and cannot be recovered afterward.
#
# Reading (cat, Read tool) and editing via Edit/Write (which read first) are
# unaffected — this only targets Bash redirection and rm/git rm.

input="$(cat)"
cmd="$(printf '%s' "$input" | jq -r '.tool_input.command // empty')"
[ -z "$cmd" ] && exit 0

# Normalize glued operators (e.g. `>.dev.vars`, `2>>file`) and separators into
# standalone whitespace-delimited tokens so naive splitting below is reliable.
# Newlines are folded to `;` first: they separate commands just as much as `;` does, and
# without this an `rm` on one line kept "looking for targets" into the lines below it,
# so an unrelated later mention of .dev.vars was misread as that rm's argument.
norm="$(printf '%s' "$cmd" | tr '\n' ';' | sed -E 's/(&>>|>>|&>|>)/ \1 /g; s/(&&|\|\||;|\|)/ \1 /g')"

is_protected() {
    local f="$1"
    f="${f%\"}"; f="${f#\"}"
    f="${f%\'}"; f="${f#\'}"
    case "$f" in
        *.example|*.example.*) return 1 ;;
        *.dev.vars|*.env|*.env.*) return 0 ;;
        *) return 1 ;;
    esac
}

blocked=""
prev=""
found_rm=0
for tok in $norm; do
    case "$tok" in
        ";" | "&&" | "||" | "|") found_rm=0 ;;
    esac
    case "$prev" in
        ">" | ">>" | "&>" | "&>>")
            if is_protected "$tok"; then blocked="redirect ($prev) into $tok"; fi
            ;;
    esac
    if [ "$found_rm" = "1" ]; then
        case "$tok" in
            -*) ;;
            *) if is_protected "$tok"; then blocked="rm targeting $tok"; fi ;;
        esac
    fi
    case "$tok" in
        rm) found_rm=1 ;;
    esac
    prev="$tok"
done

if [ -n "$blocked" ]; then
    reason="Blocked: this Bash command would overwrite or delete a .dev.vars/.env* file ($blocked). These files can hold irreplaceable credentials (e.g. a Cloudflare API token, only ever shown once at creation) -- a real incident destroyed one this way with no backup and it had to be regenerated by hand from the Cloudflare dashboard. Before touching this file: 1) back it up first, e.g. cp .dev.vars /tmp/.dev.vars.bak  2) make the change  3) restore the EXACT original content afterward instead of deleting it. To inspect or edit content safely, use the Read/Edit tools instead of Bash redirection or rm."
    jq -n --arg reason "$reason" '{
        systemMessage: $reason,
        hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: $reason
        }
    }'
fi

exit 0
